# Generated by Django 6.0.7 on 2026-08-04 00:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Criação'), ('update', 'Atualização'), ('status_change', 'Mudança de status')], max_length=32)),
                ('entity_type', models.CharField(choices=[('user', 'Usuário'), ('organization', 'Organização'), ('membership', 'Vínculo')], max_length=32)),
                ('entity_id', models.UUIDField()),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ['-created_at'],
            },
        ),
    ]
