# Generated by Django 6.0.7 on 2026-08-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Criação'), ('update', 'Atualização'), ('status_change', 'Mudança de status'), ('switch_context', 'Troca de contexto')], max_length=32),
        ),
    ]
