# Generated by Django 6.0.7 on 2026-08-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_phase4_switch_context_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Criação'), ('update', 'Atualização'), ('status_change', 'Mudança de status'), ('switch_context', 'Troca de contexto'), ('redeem', 'Resgate'), ('approve', 'Aprovação'), ('reject', 'Rejeição'), ('cancel', 'Cancelamento')], max_length=32),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(choices=[('user', 'Usuário'), ('organization', 'Organização'), ('membership', 'Vínculo'), ('invite_code', 'Código de convite'), ('join_request', 'Pedido de entrada')], max_length=32),
        ),
    ]
