# Generated by Django 6.0.7 on 2026-08-04 00:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('inactive', 'Inativa')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'organização',
                'verbose_name_plural': 'organizações',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], db_index=True, default='active', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Preparação para contexto de tenant (Fase 4).', verbose_name='organização padrão')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='entrou em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization', verbose_name='organização')),
            ],
            options={
                'verbose_name': 'vínculo usuário-organização',
                'verbose_name_plural': 'vínculos usuário-organização',
                'ordering': ['-is_default', 'joined_at'],
            },
        ),
    ]
