# Generated by Django 6.0.7 on 2026-08-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmembership',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Preferência de organização ativa no login (Fase 4).', verbose_name='organização padrão'),
        ),
    ]
