# Generated by Django 6.0.7 on 2026-08-18 01:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_phase4_switch_context_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Quem criou via API; null = Admin/legado (não conta no limite).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL, verbose_name='criada por'),
        ),
        migrations.CreateModel(
            name='OrganizationInviteCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='código')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expira em')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='null = ilimitado', null=True, verbose_name='máximo de usos')),
                ('use_count', models.PositiveIntegerField(default=0, verbose_name='usos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invite_codes', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes', to='organizations.organization', verbose_name='organização')),
            ],
            options={
                'verbose_name': 'código de convite',
                'verbose_name_plural': 'códigos de convite',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='org_invite_org_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationJoinRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=20)),
                ('message', models.CharField(blank=True, default='', max_length=500, verbose_name='mensagem')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='revisado em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='organizations.organization', verbose_name='organização')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_join_requests', to=settings.AUTH_USER_MODEL, verbose_name='revisado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL, verbose_name='solicitante')),
            ],
            options={
                'verbose_name': 'pedido de entrada',
                'verbose_name_plural': 'pedidos de entrada',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='org_join_req_org_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user', 'organization'), name='uniq_pending_join_request_per_user_org')],
            },
        ),
    ]
